<?php

namespace EntityBundle\Repository;

/**
 * attributeOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class attributeOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
