<?php

namespace EntityBundle\Repository;

/**
 * valueintegerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class valueintegerRepository extends \Doctrine\ORM\EntityRepository
{
}
