<?php

namespace EntityBundle\Repository;

/**
 * valuedateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class valuedateRepository extends \Doctrine\ORM\EntityRepository
{
}
