<?php

namespace EntityBundle\Repository;

/**
 * valuetextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class valuetextRepository extends \Doctrine\ORM\EntityRepository
{
}
