<?php

namespace EntityBundle\Repository;

/**
 * valuestringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class valuestringRepository extends \Doctrine\ORM\EntityRepository
{
}
